### ISSUE TITLE
TestStack.White.Mappings.ControlDictionaryException

### ISSUE THREAD

**Issue by starbug8866** [TestStack/White#277] opened 2015-01-06 06:21 UTC
Hi,

I am just starting out on White and I am getting the following error when trying to access the nodes of a tree within my .NET 4 app:

'An exception of type 'TestStack.White.Mappings.ControlDictionaryException' occurred in TestStack.White.dll but was not handled in user code

Additional information: Multiple TestControls found for ControlType=tree view item and FrameworkId: - TestStack.White.UIItems.TreeItems.Win32TreeNode, TestStack.White.UIItems.TreeItems.WPFTreeNode, TestStack.White.UIItems.TreeItems.Win32TreeNode'

The code is as follows:

```
List<Window> windows = application.GetWindows();
IUIItem customToolsAddInsButton = windows[0].Get(SearchCriteria.ByText("Custom Tools (Add-Ins)"));
customToolsAddInsButton.Click();

Panel customToolsPanel = windows[0].Get<Panel>(SearchCriteria.ByAutomationId("Function.CustomTools"));
				
Tree customToolsTree = customToolsPanel.Get<Tree>();

foreach(TreeNode node in customToolsTree.Nodes) // Exception thrown here
{
	// do something
}
```

I am also using Visual UI Automation Verify and can see that the nodes are there (and can see them within the app UI). Within Verify, the hierarchy looks as follows:

* "pane" "" "Function.CustomTools"
  *  "tree" "" "5376242"
    *  "tree item" "This is some text"

Any help you can give is will be appreciated.

Thanks

**Comment by JakeGinnivan** [comment] 2015-01-06 08:11
This is a bug, it was introduced when trying to prepare for newer versions of the ui automation libraries..

The issue is that the framework is not being passed down properly. I will see if I can fix it and a few other issues and get release out this week.

Sorry about the rocky start to using White

Sent from my Windows Phone
________________________________

**Comment by starbug8866** [comment] 2015-01-06 21:37
No worries, thank you for the quick response. Looking forward to the fix!

**Comment by VladislavKostyukevich** [comment] 2015-06-23 08:42
Hey,
I have the same problem. Were found some solutions?

**Comment by szabolcslevay** [comment] 2016-04-06 12:16
The issues is still not fixed.

**Comment by andrewtheart** [comment] 2016-05-12 22:40
Indeed, it does not appear to be fixed ... Jake, can you indicate when the regression was introduced so we can use a prior version?

**Comment by maninwindow** [comment] 2016-05-13 01:48
@starbug8866  I had same issue. Eventually, i fixed it myself. My solution may not be the best, but have a solution is better than nothing. https://github.com/TestStack/White/issues/411

**Comment by AustinMatherne** [comment] 2016-07-25 03:06
@JakeGinnivan have you had a chance to look into this further? I'm evaluating using White to test an app with many trees.

**Comment by JakeGinnivan** [comment] 2016-07-25 13:31
No I haven't. I'm not using White currently and can't dedicate the time to fixing this up. 

I am more than happy to add anyone as a contributor and can also skype to answer any questions I still remember but I don't think I will get to this soon.

**Comment by AustinMatherne** [comment] 2016-07-25 17:48
Thanks, I appreciate the offer. I'm about to tackle a large project with White. I'd be quite happy to be added as a contributor.

There's actually already an open pull request that resolves this issue (at least for me) #450. Can we get it merged?

**Comment by AustinMatherne** [comment] 2016-08-07 04:02
@JakeGinnivan just following up on this. Can you add me as a contributor?

**Comment by JakeGinnivan** [comment] 2016-08-11 00:46
@AustinMatherne done, sorry for the delay :)

**Comment by omireault** [comment] 2016-09-28 20:36
I didn't isolate my fix properly, so I had to restart the PR request.

**Closed** 2016-09-29 00:14 UTC

**Comment by gpomykala** [comment] 2017-02-23 13:59
can someone publish a nuget package?

**Comment by sark2323** [comment] 2017-12-06 17:05
is there a solution for this issue?
